name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  flutter_contacts: ^1.1.9+2
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.1.0
  encrypt: ^5.0.1
  crypto: ^3.0.2
  emoji_picker_flutter: ^4.3.0
  provider: ^6.1.5


flutter_native_splash:
  color: "#ffffff"  # background color
  image: "assets/icons/meetme.png"  # your splash image
  android: true
  ios: true


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/meetme.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
