// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCft2RRrPiWkqoZJBBsiiltRvHyMwZ0CbY',
    appId: '1:399946329174:web:b099180ece4989df419ff7',
    messagingSenderId: '399946329174',
    projectId: 'chat-app-8fa75',
    authDomain: 'chat-app-8fa75.firebaseapp.com',
    storageBucket: 'chat-app-8fa75.firebasestorage.app',
    measurementId: 'G-51BSR4NVS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP2poh6xT0UY9q0JLRRr_cJ0MZxqqFVAc',
    appId: '1:399946329174:android:dec8287729b5eb1e419ff7',
    messagingSenderId: '399946329174',
    projectId: 'chat-app-8fa75',
    storageBucket: 'chat-app-8fa75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFbnCJrLVyjrxSgHGrkI4uvEFp-IR3lfs',
    appId: '1:399946329174:ios:427f7284c3b476f4419ff7',
    messagingSenderId: '399946329174',
    projectId: 'chat-app-8fa75',
    storageBucket: 'chat-app-8fa75.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFbnCJrLVyjrxSgHGrkI4uvEFp-IR3lfs',
    appId: '1:399946329174:ios:427f7284c3b476f4419ff7',
    messagingSenderId: '399946329174',
    projectId: 'chat-app-8fa75',
    storageBucket: 'chat-app-8fa75.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
